import Link from "next/link";
import { getAdminDevelopers } from "@/lib/admin/queries";
import { ADMIN_TICKET_STATUS } from "@/lib/admin/status";

export const dynamic = "force-dynamic";

export default async function AdminDevelopersPage() {
  const developers = await getAdminDevelopers();
  return <div className="mx-auto max-w-[1280px] px-4 py-8 sm:px-6 lg:px-10"><header><p className="text-sm font-medium text-[#4648d4]">Administracion</p><h1 className="mt-2 text-3xl font-semibold sm:text-4xl">Developers</h1><p className="mt-3 text-sm text-[#666768]">Carga de trabajo y tickets asociados a cada Developer.</p></header>{developers.length === 0 ? <div className="mt-8 border-y border-[#e1e3e4] p-16 text-center text-sm text-[#666768]">No hay usuarios con rol Developer.</div> : <section className="mt-8 grid gap-5 xl:grid-cols-2">{developers.map((developer) => { const counts = { active: developer.ticketsAssigned.filter((t) => t.status === "PAID" || t.status === "IN_PROGRESS").length, review: developer.ticketsAssigned.filter((t) => t.status === "REVIEW").length, done: developer.ticketsAssigned.filter((t) => t.status === "DONE").length }; return <article key={developer.id} className="rounded-lg border border-[#d9dadb] bg-white p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{developer.name ?? "Developer"}</h2><p className="mt-1 text-sm text-[#666768]">{developer.email}</p></div><span className="rounded bg-[#eef0ff] px-2 py-1 text-xs font-medium text-[#4648d4]">DEV</span></div><dl className="mt-5 grid grid-cols-3 gap-3 border-y border-[#eceeef] py-4 text-center"><div><dd className="text-xl font-semibold">{counts.active}</dd><dt className="mt-1 text-xs text-[#777879]">Activos</dt></div><div><dd className="text-xl font-semibold">{counts.review}</dd><dt className="mt-1 text-xs text-[#777879]">Revision</dt></div><div><dd className="text-xl font-semibold">{counts.done}</dd><dt className="mt-1 text-xs text-[#777879]">Completados</dt></div></dl><h3 className="mt-5 text-xs font-semibold uppercase text-[#777879]">Tickets recientes</h3>{developer.ticketsAssigned.length === 0 ? <p className="mt-3 text-sm text-[#666768]">Sin tickets asociados.</p> : <ul className="mt-3 divide-y divide-[#eceeef]">{developer.ticketsAssigned.slice(0, 5).map((ticket) => <li key={ticket.id}><Link href={`/admin/tickets/${ticket.id}`} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{ticket.title}</p><p className="mt-1 truncate text-xs text-[#777879]">{ticket.project.name}</p></div><span className="shrink-0 text-xs text-[#4648d4]">{ADMIN_TICKET_STATUS[ticket.status]}</span></Link></li>)}</ul>}</article>; })}</section>}</div>;
}
