import Link from "next/link";
import { ConfirmPaymentButton } from "@/components/admin/admin-action-button";
import { getAdminPayments } from "@/lib/admin/queries";
import { money } from "@/lib/admin/status";

export const dynamic = "force-dynamic";
const date = new Intl.DateTimeFormat("es-AR", { dateStyle: "medium" });

export default async function AdminPaymentsPage() {
  const { acceptedQuotes, transactions } = await getAdminPayments();
  return <div className="mx-auto max-w-[1280px] px-4 py-8 sm:px-6 lg:px-10"><header><p className="text-sm font-medium text-[#4648d4]">Administracion</p><h1 className="mt-2 text-3xl font-semibold sm:text-4xl">Pagos</h1><p className="mt-3 text-sm text-[#666768]">Confirma pagos del MVP y habilita tickets para Developers.</p></header><section className="mt-8 rounded-lg border border-[#d9dadb]"><div className="border-b border-[#e1e3e4] p-5"><h2 className="font-semibold">Pendientes de confirmacion</h2><p className="mt-1 text-sm text-[#666768]">Cotizaciones aceptadas por el cliente.</p></div>{acceptedQuotes.length === 0 ? <p className="p-10 text-center text-sm text-[#666768]">No hay pagos pendientes.</p> : <ul className="divide-y divide-[#eceeef]">{acceptedQuotes.map((quote) => <li key={quote.id} className="flex flex-col gap-4 px-5 py-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><Link href={`/admin/tickets/${quote.ticket.id}`} className="font-semibold hover:text-[#4648d4]">{quote.ticket.title}</Link><p className="mt-1 text-xs text-[#777879]">{quote.ticket.project.name} · {quote.ticket.createdBy.name ?? quote.ticket.createdBy.email}</p></div><div className="sm:text-right"><p className="font-semibold">{money(quote.amount, quote.currency)}</p><p className="mt-1 text-xs text-[#777879]">{quote.estimatedDays ? `${quote.estimatedDays} dias habiles` : "Sin tiempo"}</p></div><ConfirmPaymentButton quoteId={quote.id} /></li>)}</ul>}</section><section className="mt-8 overflow-hidden rounded-lg border border-[#d9dadb]"><div className="border-b border-[#e1e3e4] p-5"><h2 className="font-semibold">Transacciones</h2><p className="mt-1 text-sm text-[#666768]">Ultimos pagos registrados.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[#e1e3e4] bg-[#f8f9fa] text-xs uppercase text-[#777879]"><tr><th className="px-5 py-3">Fecha</th><th>Ticket</th><th>Importe</th><th>Proveedor</th><th>Estado</th></tr></thead><tbody className="divide-y divide-[#eceeef]">{transactions.map((item) => <tr key={item.id}><td className="px-5 py-4">{date.format(item.createdAt)}</td><td>{item.ticket ? <Link href={`/admin/tickets/${item.ticket.id}`} className="font-medium hover:text-[#4648d4]">{item.ticket.title}</Link> : "Sin ticket"}</td><td>{money(item.amount, item.currency)}</td><td>{item.provider}</td><td>{item.status}</td></tr>)}</tbody></table></div>{transactions.length === 0 && <p className="p-10 text-center text-sm text-[#666768]">No hay transacciones registradas.</p>}</section></div>;
}
